#!/bin/sh

while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"k")	
		kdeconnect-cli --refresh
		sleep 2
		kdeconnect-cli -n 'Phone' --share "$fullpath" &&
		notify-send -a 'Kde Connect' 'Files sent...' -i 'dialog-information' -t 5000 ||
		notify-send -a 'Kde Connect' 'Files not sent...' -i 'dialog-error' -t 5000 ;;
	"w")
		# nitrogen --save --set-zoom-fill $fullpath &&
		feh --bg-fill $fullpath &&
		wal -i $fullpath &&
		xrdb ~/.Xresources &&
		bash /home/dilip/.scripts/genzathurarc >> ~/.config/zathura/zathurarc &&
		notify-send -a 'Sxiv' 'Theme changed...' -i 'nitrogen' ;;
	"W")
		mantablockscreen -i $fullpath &&
		notify-send -a 'Sxiv' 'Lockscreen changed...' -i 'nitrogen' ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"h")
		convert -flop "$file" "$file" ;;
	"v")
		convert -flip "$file" "$file" ;;
	"D")
		trash-put "$file" ;;
	esac
done
