#!/bin/sh
#  __                                  
# |  |--.-----.-----.--.--.--.--------.
# |  _  |__ --|  _  |  |  |  |        |
# |_____|_____|   __|________|__|__|__|
#             |__|  

# SETTINGS {{{
. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d   "" "" "" "" "" "嗢" "" "" "" 

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config normal_border_color "$background"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color4"
bspc config focus_follows_pointer true

# }}}

# RULES {{{

bspc rule -a Zathura state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Pavucontrol state=pseudo_tiled
bspc rule -a SimpleScreenRecorder state=pseudo_tiled

# }}}

# AUTOSTART {{{

# nitrogen --restore &
urxvtd -q -o -f &
./.fehbg
wal -R
# ./.config/polybar/launch.sh bspwm-bar &
polybar -c .config/polybar/float-bar bspwm-bar-left &
polybar -c .config/polybar/float-bar bspwm-bar-right &
nm-applet &
dunst -sep_color "$background" -frame_color "$color4" -nf "$foreground" -lf "$foreground" -cf "$foreground" &
kdeconnect-indicator &
picom --experimental-backend &
# telegram-desktop -startintray &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# }}}
